// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sidekick.Data.Ninja;

#nullable disable

namespace Sidekick.Data.Ninja.Migrations
{
    [DbContext(typeof(NinjaDbContext))]
    [Migration("20260627170435_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Sidekick.Data.Ninja.Models.NinjaExchangeItem", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("Game", "Type");

                    b.ToTable("NinjaExchangeItems");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.Models.NinjaStashItem", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Corrupted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailsId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GemQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Links")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.ToTable("NinjaStashItems");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.Models.NinjaStashMutatedStat", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Optional")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StashItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("StashItemId");

                    b.ToTable("NinjaStashMutatedStats");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.Models.NinjaStashTradeStat", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mod")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StashItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("StashItemId");

                    b.ToTable("NinjaStashTradeStats");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.Models.NinjaStashMutatedStat", b =>
                {
                    b.HasOne("Sidekick.Data.Ninja.Models.NinjaStashItem", "StashItem")
                        .WithMany("MutatedStats")
                        .HasForeignKey("StashItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StashItem");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.Models.NinjaStashTradeStat", b =>
                {
                    b.HasOne("Sidekick.Data.Ninja.Models.NinjaStashItem", "StashItem")
                        .WithMany("TradeStats")
                        .HasForeignKey("StashItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StashItem");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.Models.NinjaStashItem", b =>
                {
                    b.Navigation("MutatedStats");

                    b.Navigation("TradeStats");
                });
#pragma warning restore 612, 618
        }
    }
}
