// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sidekick.Data.Ninja;

#nullable disable

namespace Sidekick.Data.Ninja.Migrations
{
    [DbContext(typeof(NinjaDbContext))]
    partial class NinjaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Sidekick.Data.Ninja.Models.NinjaExchangeItem", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ChaosValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyDetailsId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("Game", "Type");

                    b.ToTable("ExchangeItems");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.Models.NinjaStashItem", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Corrupted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailsId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GemQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Links")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("Game", "Type");

                    b.ToTable("StashItems");
                });
#pragma warning restore 612, 618
        }
    }
}
