// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sidekick.Data.Trade;

#nullable disable

namespace Sidekick.Data.Trade.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    [Migration("20260621015409_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilter", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeItem", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsUnique")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.HasIndex("Game", "Language", "CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeItemCategory", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeLeague", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Realm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStat", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("OptionText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.HasIndex("Game", "Language", "CategoryId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStatCategory", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("StatCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStaticItem", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.HasIndex("Game", "Language", "CategoryId");

                    b.ToTable("StaticItems");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStaticItemCategory", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("StaticItemCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeItem", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("Game", "Language", "CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStat", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeStatCategory", "Category")
                        .WithMany()
                        .HasForeignKey("Game", "Language", "CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStaticItem", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeStaticItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("Game", "Language", "CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
