// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sidekick.Data.Trade;

#nullable disable

namespace Sidekick.Data.Trade.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    [Migration("20260622013938_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilter", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FullSpan")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HalfSpan")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("MinMax")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Sockets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilterOption", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterGroupId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "FilterGroupId", "FilterId", "Id");

                    b.HasIndex("Game", "Language", "FilterId");

                    b.ToTable("FilterOptions");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeItem", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeLeague", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Realm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStat", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStatOption", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "StatId", "Id");

                    b.ToTable("StatOptions");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStaticItem", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("StaticItems");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilterOption", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeFilter", null)
                        .WithMany("Options")
                        .HasForeignKey("Game", "Language", "FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStatOption", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeStat", null)
                        .WithMany("Options")
                        .HasForeignKey("Game", "Language", "StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilter", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStat", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
