// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sidekick.Data.Trade;

#nullable disable

namespace Sidekick.Data.Trade.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    [Migration("20260624183307_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilter", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FullSpan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HalfSpan")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("MinMax")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Sockets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilterCategory", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("FilterCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilterOption", b =>
                {
                    b.Property<Guid>("FilterUniqueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("FilterUniqueId", "Id");

                    b.ToTable("FilterOptions");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeItem", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Game", "Language", "CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeItemCategory", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeLeague", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Realm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Game", "Language", "Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStat", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStatCategory", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("StatCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStatOption", b =>
                {
                    b.Property<Guid>("TradeStatUniqueId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("TradeStatUniqueId", "Id");

                    b.ToTable("StatOptions");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStaticItem", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("StaticItems");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStaticItemCategory", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("StaticItemCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilter", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeFilterCategory", "Category")
                        .WithMany("Children")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilterOption", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeFilter", "TradeFilter")
                        .WithMany("Options")
                        .HasForeignKey("FilterUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeFilter");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeItem", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeItemCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStat", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeStatCategory", "Category")
                        .WithMany("Stats")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStatOption", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeStat", "TradeStat")
                        .WithMany("Options")
                        .HasForeignKey("TradeStatUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeStat");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStaticItem", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.Models.TradeStaticItemCategory", "Category")
                        .WithMany("StaticItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilter", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeFilterCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeItemCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStat", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStatCategory", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.Models.TradeStaticItemCategory", b =>
                {
                    b.Navigation("StaticItems");
                });
#pragma warning restore 612, 618
        }
    }
}
