// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sidekick.Data;

#nullable disable

namespace Sidekick.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20260629212213_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("ItemDefinitionEntityNinjaStashItem", b =>
                {
                    b.Property<Guid>("ItemDefinitionsSidekickId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NinjaStashItemsSidekickId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemDefinitionsSidekickId", "NinjaStashItemsSidekickId");

                    b.HasIndex("NinjaStashItemsSidekickId");

                    b.ToTable("ItemDefinitionEntityNinjaStashItem");
                });

            modelBuilder.Entity("Sidekick.Data.BaseItems.BaseItem", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ArmourMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArmourMin")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AttacksPerSecond")
                        .HasColumnType("REAL");

                    b.Property<int?>("Block")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CriticalHitChance")
                        .HasColumnType("REAL");

                    b.Property<int?>("DropLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnergyShieldMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnergyShieldMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EvasionMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EvasionMin")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ItemClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhysicalDamageMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhysicalDamageMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiresDexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiresIntelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiresStrength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WardMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WardMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("SidekickId");

                    b.HasIndex("ItemClassId");

                    b.HasIndex("Game", "Language");

                    b.ToTable("BaseItems");
                });

            modelBuilder.Entity("Sidekick.Data.ItemClasses.ItemClassEntity", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("SidekickId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("ItemClasses");
                });

            modelBuilder.Entity("Sidekick.Data.ItemDefinitions.ItemDefinitionEntity", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BaseItemId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePattern")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NinjaExchangeItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextPattern")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TradeItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypePattern")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UniqueItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("BaseItemId");

                    b.HasIndex("NinjaExchangeItemId");

                    b.HasIndex("TradeItemId");

                    b.HasIndex("UniqueItemId");

                    b.HasIndex("Game", "Language");

                    b.ToTable("ItemDefinitions");
                });

            modelBuilder.Entity("Sidekick.Data.ItemDefinitions.UniqueItemEntity", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ItemClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("ItemClassId");

                    b.HasIndex("Game", "Language");

                    b.ToTable("UniqueItems");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.NinjaExchangeItem", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("Game", "Type");

                    b.ToTable("NinjaExchangeItems");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.NinjaStashItem", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Corrupted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailsId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GemQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Links")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.ToTable("NinjaStashItems");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.NinjaStashMutatedStat", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Optional")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StashItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("StashItemId");

                    b.ToTable("NinjaStashMutatedStats");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.NinjaStashTradeStat", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mod")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Option")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StashItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("StashItemId");

                    b.ToTable("NinjaStashTradeStats");
                });

            modelBuilder.Entity("Sidekick.Data.StatsInvariant.StatsInvariantColdWeaponDamage", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.ToTable("StatsInvariantColdWeaponDamage");
                });

            modelBuilder.Entity("Sidekick.Data.StatsInvariant.StatsInvariantFireWeaponDamage", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.ToTable("StatsInvariantFireWeaponDamage");
                });

            modelBuilder.Entity("Sidekick.Data.StatsInvariant.StatsInvariantIgnore", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.ToTable("StatsInvariantIgnore");
                });

            modelBuilder.Entity("Sidekick.Data.StatsInvariant.StatsInvariantIncursionRoom", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.ToTable("StatsInvariantIncursionRoom");
                });

            modelBuilder.Entity("Sidekick.Data.StatsInvariant.StatsInvariantLightningWeaponDamage", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.ToTable("StatsInvariantLightningWeaponDamage");
                });

            modelBuilder.Entity("Sidekick.Data.StatsInvariant.StatsInvariantLogbookBoss", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.ToTable("StatsInvariantLogbookBoss");
                });

            modelBuilder.Entity("Sidekick.Data.StatsInvariant.StatsInvariantLogbookFaction", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.ToTable("StatsInvariantLogbookFaction");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeFilter", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FullSpan")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HalfSpan")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("MinMax")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Sockets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("TradeFilters");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeFilterCategory", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("TradeFilterCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeFilterOption", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FilterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("FilterId");

                    b.ToTable("TradeFilterOptions");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeItem", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StaticItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StaticItemId");

                    b.HasIndex("Game", "Language");

                    b.ToTable("TradeItems");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeItemCategory", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("TradeItemCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeLeague", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Realm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("TradeLeagues");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeStat", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionText")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("TradeStats");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeStatCategory", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("TradeStatCategories");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeStaticItem", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("TradeStaticItems");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeStaticItemCategory", b =>
                {
                    b.Property<Guid>("SidekickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("SidekickId");

                    b.HasIndex("Game", "Language", "Id");

                    b.ToTable("TradeStaticItemCategories");
                });

            modelBuilder.Entity("ItemDefinitionEntityNinjaStashItem", b =>
                {
                    b.HasOne("Sidekick.Data.ItemDefinitions.ItemDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("ItemDefinitionsSidekickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sidekick.Data.Ninja.NinjaStashItem", null)
                        .WithMany()
                        .HasForeignKey("NinjaStashItemsSidekickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sidekick.Data.BaseItems.BaseItem", b =>
                {
                    b.HasOne("Sidekick.Data.ItemClasses.ItemClassEntity", "ItemClass")
                        .WithMany()
                        .HasForeignKey("ItemClassId");

                    b.Navigation("ItemClass");
                });

            modelBuilder.Entity("Sidekick.Data.ItemDefinitions.ItemDefinitionEntity", b =>
                {
                    b.HasOne("Sidekick.Data.BaseItems.BaseItem", "BaseItem")
                        .WithMany()
                        .HasForeignKey("BaseItemId");

                    b.HasOne("Sidekick.Data.Ninja.NinjaExchangeItem", "NinjaExchangeItem")
                        .WithMany()
                        .HasForeignKey("NinjaExchangeItemId");

                    b.HasOne("Sidekick.Data.Trade.TradeItem", "TradeItem")
                        .WithMany()
                        .HasForeignKey("TradeItemId");

                    b.HasOne("Sidekick.Data.ItemDefinitions.UniqueItemEntity", "UniqueItem")
                        .WithMany()
                        .HasForeignKey("UniqueItemId");

                    b.Navigation("BaseItem");

                    b.Navigation("NinjaExchangeItem");

                    b.Navigation("TradeItem");

                    b.Navigation("UniqueItem");
                });

            modelBuilder.Entity("Sidekick.Data.ItemDefinitions.UniqueItemEntity", b =>
                {
                    b.HasOne("Sidekick.Data.ItemClasses.ItemClassEntity", "ItemClass")
                        .WithMany()
                        .HasForeignKey("ItemClassId");

                    b.Navigation("ItemClass");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.NinjaStashMutatedStat", b =>
                {
                    b.HasOne("Sidekick.Data.Ninja.NinjaStashItem", "StashItem")
                        .WithMany("MutatedStats")
                        .HasForeignKey("StashItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StashItem");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.NinjaStashTradeStat", b =>
                {
                    b.HasOne("Sidekick.Data.Ninja.NinjaStashItem", "StashItem")
                        .WithMany("TradeStats")
                        .HasForeignKey("StashItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StashItem");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeFilter", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.TradeFilterCategory", "Category")
                        .WithMany("Filters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeFilterOption", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.TradeFilter", "TradeFilter")
                        .WithMany("Options")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeFilter");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeItem", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.TradeItemCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sidekick.Data.Trade.TradeStaticItem", "StaticItem")
                        .WithMany()
                        .HasForeignKey("StaticItemId");

                    b.Navigation("Category");

                    b.Navigation("StaticItem");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeStat", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.TradeStatCategory", "Category")
                        .WithMany("Stats")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeStaticItem", b =>
                {
                    b.HasOne("Sidekick.Data.Trade.TradeStaticItemCategory", "Category")
                        .WithMany("StaticItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sidekick.Data.Ninja.NinjaStashItem", b =>
                {
                    b.Navigation("MutatedStats");

                    b.Navigation("TradeStats");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeFilter", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeFilterCategory", b =>
                {
                    b.Navigation("Filters");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeItemCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeStatCategory", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Sidekick.Data.Trade.TradeStaticItemCategory", b =>
                {
                    b.Navigation("StaticItems");
                });
#pragma warning restore 612, 618
        }
    }
}
